# Generated by Django 4.0 on 2024-02-24 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Post',
            new_name='Lostik',
        ),
    ]
