# Generated by Django 4.0 on 2024-03-03 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_remove_post_photo_post_created_at_post_is_actual_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post 16', max_length=128, null=True),
        ),
    ]
