# Generated by Django 4.0 on 2024-03-03 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_alter_post_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(default='post 35', max_length=128, null=True),
        ),
    ]
